"""two

Revision ID: ecdde93b4f2f
Revises: 8e4ed9b6ed2e
Create Date: 2025-04-21 11:07:14.851192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecdde93b4f2f'
down_revision: Union[str, None] = '8e4ed9b6ed2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['id'])
    op.alter_column('transactions', 'id_category',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'transactions', ['id'])
    op.drop_constraint('transactions_id_category_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'categories', ['id_category'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_id_category_fkey', 'transactions', 'categories', ['id_category'], ['id'])
    op.drop_constraint(None, 'transactions', type_='unique')
    op.alter_column('transactions', 'id_category',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
